[package]
name = 'actions'
version = '0.0.1'
edition = '2018'
[dependencies.ast]
version = '0.0.1'
path = '../ast'

[dependencies.log]
version = '>= 0.4.14'

[dependencies.thiserror]
version = '>= 1.0.30'
