[package]
name = 'cli'
version = '0.0.1'
edition = '2018'
[dependencies.log]
version = '>= 0.4.14'

[dependencies.parse]
version = '0.0.1'
path = '../parse'

[dependencies.pretty_env_logger]
version = '>= 0.4.0'

[dependencies.thiserror]
version = '>= 1.0.30'
